#!/bin/bash

# GNU Affero General Public License v3.0

# void environment setup
# run script after fresh void installation

main() {

  cd ~/;
  clear;
  echo -e "\n";
  
  # packages to be installed
  # modify as needed (double check array syntax)
  programs=(
	  "git" "xorg" "lxde"
	  "neovim" "zip" "unzip" 
	  "lynx" "firefox" "evince" 
	  "feh" "gimp" "gpick"
	  "android-tools" "cmus"
	  );

  # set current date
  set_date() {

    clear
    
    # date confirmed
    date_confirmed() {
      sudo date --set ""$current_year"-"$current_month"-"$current_day" "$current_hour":"$current_minute":00";
    }

    # input date/time
    echo -e "\n## set date ##\n";
    
    # input date
    read -p "year: " current_year;
    read -p "month: " current_month;
    read -p "day: " current_day;
    
    # input time
    read -p "hour (24h format): " current_hour;
    read -p "minute: " current_minute;

    # confirm date
    echo -e "\n## "$current_year"-"$current_month"-"$current_day" "$current_hour":"$current_minute":00 ##\n";
    read -p "confirm date? " confirm_date;
    if [[ "$confirm_date" = "y" ]] || [[ "$confirm_date" = "ye" ]] || [[ "$confirm_date" = "yes" ]]
    then
      date_confirmed;
    else
      set_date;
    fi
  }
  
  # get date
  read -p "set date? (y/n): " get_date_prompt;
  if [[ "$get_date_prompt" = "y" ]] || [[ "$get_date_prompt" = "ye" ]] || [[ "$get_date_prompt" = "yes" ]]
  then
    set_date;
  fi
  
  sleep 1;
  echo -e "\n";
  
  # update repo
  echo -e "\nupdating repo...";
  xbps-install -u xbps;
  xbps-install -Su;

  #pkg install
  echo -e "\ninstalling selected packages...";
  for program in "${programs[@]}"
  do
    yes | sudo xbps-install -S "$program";
  done

  # create sym link to dm
  # boot into de
  echo -e "\ncreating display manager sym link...";
  echo -e "booting into desktop environment...";
  ln -s /etc/sv/lxdm /var/service;
}

main
